services:
  - type: web
    name: rag-multiagent
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.application:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    autoDeploy: true 